/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diagnose
         * @description Millisecond necessary-condition checks (L1).
         */
        post: operations["diagnose_api_diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain
         * @description Soft-relax diagnostic (L3). ~30 s — use only after an INFEASIBLE solve.
         */
        post: operations["explain_api_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overrides/fill-from-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fill From Snapshot
         * @description Copy assignments from a completed solve into the overrides list.
         *
         *     `snapshot_id` is "final" for the last result, or the 0-based index
         *     (as a string) of an intermediate event from the same solve.
         */
        post: operations["fill_from_snapshot_api_overrides_fill_from_snapshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_api_state_get"];
        /** Put State */
        put: operations["put_state_api_state_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch State */
        patch: operations["patch_state_api_state_patch"];
        trace?: never;
    };
    "/api/state/prev_workload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute Prev Workload
         * @description Compute prev_workload from a prior-period roster JSON and apply it in place.
         *
         *     Returns the updated doctors list so the client can diff what changed.
         */
        post: operations["compute_prev_workload_api_state_prev_workload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Sample
         * @description Load the known-feasible 15-doctor × 7-day sample config bundled in the
         *     repo at configs/sample_feasible.yaml. Proves the solver works end-to-end
         *     and gives the user a starting point they can tweak.
         */
        post: operations["load_sample_api_state_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Defaults
         * @description Replace the session with a sensible default roster problem.
         *
         *     Useful for the SPA's empty-state "Start with defaults" button.
         */
        post: operations["seed_defaults_api_state_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Yaml */
        get: operations["export_yaml_api_state_yaml_get"];
        put?: never;
        /** Import Yaml */
        post: operations["import_yaml_api_state_yaml_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlockEntry */
        BlockEntry: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Doctor */
            doctor: string;
            /** End Date */
            end_date?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "Leave" | "No on-call" | "No AM" | "No PM" | "Prefer AM" | "Prefer PM";
        };
        /** ConstraintsConfig */
        ConstraintsConfig: {
            /**
             * H11 Enabled
             * @default true
             */
            h11_enabled: boolean;
            /**
             * H4 Enabled
             * @default true
             */
            h4_enabled: boolean;
            /**
             * H4 Gap
             * @default 3
             */
            h4_gap: number;
            /**
             * H5 Enabled
             * @default true
             */
            h5_enabled: boolean;
            /**
             * H6 Enabled
             * @default true
             */
            h6_enabled: boolean;
            /**
             * H7 Enabled
             * @default true
             */
            h7_enabled: boolean;
            /**
             * H8 Enabled
             * @default true
             */
            h8_enabled: boolean;
            /**
             * H9 Enabled
             * @default true
             */
            h9_enabled: boolean;
            /**
             * Weekend Am Pm
             * @default false
             */
            weekend_am_pm: boolean;
        };
        /** DoctorEntry */
        DoctorEntry: {
            /** Eligible Stations */
            eligible_stations?: string[];
            /**
             * Fte
             * @default 1
             */
            fte: number;
            /** Max Oncalls */
            max_oncalls?: number | null;
            /** Name */
            name: string;
            /**
             * Prev Workload
             * @default 0
             */
            prev_workload: number;
            /** Subspec */
            subspec?: string | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "junior" | "senior" | "consultant";
        };
        /** ExplainReport */
        ExplainReport: {
            /**
             * Note
             * @default
             */
            note: string;
            /** Status */
            status: string;
            /** Total Slack */
            total_slack: number;
            /** Violations */
            violations: components["schemas"]["ExplainViolation"][];
            /** Wall Time S */
            wall_time_s: number;
        };
        /** ExplainViolation */
        ExplainViolation: {
            /** Amount */
            amount: number;
            /** Code */
            code: string;
            /** Location */
            location: string;
            /** Message */
            message: string;
        };
        /** FeasibilityIssueOut */
        FeasibilityIssueOut: {
            /** Code */
            code: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning" | "info";
        };
        /**
         * FillFromSnapshotRequest
         * @description Copy assignments from a completed solve into the overrides list.
         *
         *     `snapshot_id` is either "final" or the 0-based index of an intermediate
         *     solve event from the last solve.
         */
        FillFromSnapshotRequest: {
            /**
             * Snapshot Id
             * @default final
             */
            snapshot_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Horizon */
        Horizon: {
            /**
             * N Days
             * @default 21
             */
            n_days: number;
            /** Public Holidays */
            public_holidays?: string[];
            /** Start Date */
            start_date?: string | null;
        };
        /** Hours */
        Hours: {
            /**
             * Weekday Am
             * @default 4
             */
            weekday_am: number;
            /**
             * Weekday Oncall
             * @default 12
             */
            weekday_oncall: number;
            /**
             * Weekday Pm
             * @default 4
             */
            weekday_pm: number;
            /**
             * Weekend Am
             * @default 4
             */
            weekend_am: number;
            /**
             * Weekend Consult
             * @default 8
             */
            weekend_consult: number;
            /**
             * Weekend Ext
             * @default 12
             */
            weekend_ext: number;
            /**
             * Weekend Oncall
             * @default 16
             */
            weekend_oncall: number;
            /**
             * Weekend Pm
             * @default 4
             */
            weekend_pm: number;
        };
        /** OverrideEntry */
        OverrideEntry: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Doctor */
            doctor: string;
            /** Role */
            role: string;
        };
        /** PrevWorkloadRequest */
        PrevWorkloadRequest: {
            /** Prev Roster Json */
            prev_roster_json: {
                [key: string]: unknown;
            };
        };
        /** SessionState */
        SessionState: {
            /** Blocks */
            blocks?: components["schemas"]["BlockEntry"][];
            constraints?: components["schemas"]["ConstraintsConfig"];
            /** Doctors */
            doctors?: components["schemas"]["DoctorEntry"][];
            horizon?: components["schemas"]["Horizon"];
            hours?: components["schemas"]["Hours"];
            /** Overrides */
            overrides?: components["schemas"]["OverrideEntry"][];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            soft_weights?: components["schemas"]["SoftWeights"];
            solver?: components["schemas"]["SolverSettings"];
            /** Stations */
            stations?: components["schemas"]["StationEntry"][];
            /** Subspecs */
            subspecs?: string[];
            tier_labels?: components["schemas"]["TierLabels"];
            workload_weights?: components["schemas"]["WorkloadWeights"];
        };
        /** SoftWeights */
        SoftWeights: {
            /**
             * Idle Weekday
             * @default 100
             */
            idle_weekday: number;
            /**
             * Oncall
             * @default 10
             */
            oncall: number;
            /**
             * Preference
             * @default 5
             */
            preference: number;
            /**
             * Reporting
             * @default 5
             */
            reporting: number;
            /**
             * Sessions
             * @default 5
             */
            sessions: number;
            /**
             * Weekend
             * @default 10
             */
            weekend: number;
            /**
             * Workload
             * @default 40
             */
            workload: number;
        };
        /** SolverSettings */
        SolverSettings: {
            /**
             * Feasibility Only
             * @default false
             */
            feasibility_only: boolean;
            /**
             * Num Workers
             * @default 8
             */
            num_workers: number;
            /**
             * Time Limit
             * @default 60
             */
            time_limit: number;
        };
        /** StationEntry */
        StationEntry: {
            /** Eligible Tiers */
            eligible_tiers?: ("junior" | "senior" | "consultant")[];
            /**
             * Is Reporting
             * @default false
             */
            is_reporting: boolean;
            /** Name */
            name: string;
            /**
             * Required Per Session
             * @default 1
             */
            required_per_session: number;
            /** Sessions */
            sessions?: ("AM" | "PM")[];
        };
        /** TierLabels */
        TierLabels: {
            /**
             * Consultant
             * @default Consultant
             */
            consultant: string;
            /**
             * Junior
             * @default Junior
             */
            junior: string;
            /**
             * Senior
             * @default Senior
             */
            senior: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkloadWeights */
        WorkloadWeights: {
            /**
             * Weekday Oncall
             * @default 20
             */
            weekday_oncall: number;
            /**
             * Weekday Session
             * @default 10
             */
            weekday_session: number;
            /**
             * Weekend Consult
             * @default 25
             */
            weekend_consult: number;
            /**
             * Weekend Ext
             * @default 20
             */
            weekend_ext: number;
            /**
             * Weekend Oncall
             * @default 35
             */
            weekend_oncall: number;
            /**
             * Weekend Session
             * @default 15
             */
            weekend_session: number;
        };
        /** YamlExportResponse */
        YamlExportResponse: {
            /** Yaml */
            yaml: string;
        };
        /** YamlImportRequest */
        YamlImportRequest: {
            /** Yaml */
            yaml: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    diagnose_api_diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeasibilityIssueOut"][];
                };
            };
        };
    };
    explain_api_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainReport"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    fill_from_snapshot_api_overrides_fill_from_snapshot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FillFromSnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
        };
    };
    put_state_api_state_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionState"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_state_api_state_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_prev_workload_api_state_prev_workload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrevWorkloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_sample_api_state_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
        };
    };
    seed_defaults_api_state_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
        };
    };
    export_yaml_api_state_yaml_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YamlExportResponse"];
                };
            };
        };
    };
    import_yaml_api_state_yaml_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YamlImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
