/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diagnose
         * @description Millisecond necessary-condition checks (L1).
         */
        post: operations["diagnose_api_diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain
         * @description Soft-relax diagnostic (L3). ~30 s — use only after an INFEASIBLE solve.
         */
        post: operations["explain_api_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/fairness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fairness
         * @description FTE-aware per-tier fairness metrics for a caller-provided roster.
         *
         *     Formulae documented in `docs/RESEARCH_METRICS.md §4`. Reports Gini
         *     (our convention) + CV (NRP-literature standard) alongside range,
         *     std, mean, and per-individual delta-from-median.
         */
        post: operations["fairness_api_metrics_fairness_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overrides/fill-from-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fill From Snapshot
         * @description Copy assignments from a completed solve into the overrides list.
         *
         *     `snapshot_id` is "final" for the last result, or the 0-based index
         *     (as a string) of an intermediate event from the same solve.
         */
        post: operations["fill_from_snapshot_api_overrides_fill_from_snapshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roster/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Roster
         * @description Run hard-constraint checks on a caller-provided assignment list.
         *     Does not run the solver — pure validation.
         */
        post: operations["validate_roster_api_roster_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solve/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solve Sync
         * @description Blocking REST solve. Used as a fallback when the /api/solve WebSocket
         *     can't stay open through a proxy (HF Spaces sometimes drops WS mid-solve
         *     with code 1006). No intermediate events — just the final result.
         *
         *     FastAPI runs sync routes on a thread pool, so the CP-SAT work here
         *     doesn't block other requests.
         */
        post: operations["solve_sync_api_solve_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_api_state_get"];
        /** Put State */
        put: operations["put_state_api_state_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch State */
        patch: operations["patch_state_api_state_patch"];
        trace?: never;
    };
    "/api/state/prev_workload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute Prev Workload
         * @description Compute prev_workload from a prior-period roster JSON and apply it in place.
         *
         *     Returns the updated doctors list so the client can diff what changed.
         */
        post: operations["compute_prev_workload_api_state_prev_workload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Sample */
        post: operations["load_sample_api_state_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scenarios
         * @description Return the manifest of pre-built scenarios (id, title, description,
         *     stats, highlights) for the SPA's scenario picker.
         */
        get: operations["list_scenarios_api_state_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Scenario
         * @description Load one of the bundled scenarios into the current session.
         */
        post: operations["load_scenario_api_state_scenarios__scenario_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Defaults
         * @description Replace the session with a sensible default roster problem.
         *
         *     Useful for the SPA's empty-state "Start with defaults" button.
         */
        post: operations["seed_defaults_api_state_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Yaml */
        get: operations["export_yaml_api_state_yaml_get"];
        put?: never;
        /** Import Yaml */
        post: operations["import_yaml_api_state_yaml_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssignmentRow
         * @description One role a doctor was assigned on a specific date.
         *
         *     `role` follows the v1 export convention:
         *       - STATION_<station>_<AM|PM>
         *       - ONCALL
         *       - WEEKEND_EXT
         *       - WEEKEND_CONSULT
         */
        AssignmentRow: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Doctor */
            doctor: string;
            /** Role */
            role: string;
        };
        /** BlockEntry */
        BlockEntry: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Doctor */
            doctor: string;
            /** End Date */
            end_date?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "Leave" | "No on-call" | "No AM" | "No PM" | "Prefer AM" | "Prefer PM";
        };
        /** ConstraintsConfig */
        ConstraintsConfig: {
            /**
             * H11 Enabled
             * @default true
             */
            h11_enabled: boolean;
            /**
             * H4 Enabled
             * @default true
             */
            h4_enabled: boolean;
            /**
             * H4 Gap
             * @default 3
             */
            h4_gap: number;
            /**
             * H5 Enabled
             * @default true
             */
            h5_enabled: boolean;
            /**
             * H6 Enabled
             * @default true
             */
            h6_enabled: boolean;
            /**
             * H7 Enabled
             * @default true
             */
            h7_enabled: boolean;
            /**
             * H8 Enabled
             * @default true
             */
            h8_enabled: boolean;
            /**
             * H9 Enabled
             * @default true
             */
            h9_enabled: boolean;
            /**
             * Weekday Oncall Coverage
             * @default true
             */
            weekday_oncall_coverage: boolean;
            /**
             * Weekend Am Pm
             * @default false
             */
            weekend_am_pm: boolean;
        };
        /** DoctorEntry */
        DoctorEntry: {
            /** Eligible Stations */
            eligible_stations?: string[];
            /**
             * Fte
             * @default 1
             */
            fte: number;
            /** Max Oncalls */
            max_oncalls?: number | null;
            /** Name */
            name: string;
            /**
             * Prev Workload
             * @default 0
             */
            prev_workload: number;
            /** Subspec */
            subspec?: string | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "junior" | "senior" | "consultant";
        };
        /** ExplainReport */
        ExplainReport: {
            /**
             * Note
             * @default
             */
            note: string;
            /** Status */
            status: string;
            /** Total Slack */
            total_slack: number;
            /** Violations */
            violations: components["schemas"]["ExplainViolation"][];
            /** Wall Time S */
            wall_time_s: number;
        };
        /** ExplainViolation */
        ExplainViolation: {
            /** Amount */
            amount: number;
            /** Code */
            code: string;
            /** Location */
            location: string;
            /** Message */
            message: string;
        };
        /** FairnessRequest */
        FairnessRequest: {
            /** Assignments */
            assignments: components["schemas"]["AssignmentRow"][];
        };
        /** FeasibilityIssueOut */
        FeasibilityIssueOut: {
            /** Code */
            code: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning" | "info";
        };
        /**
         * FillFromSnapshotRequest
         * @description Copy assignments from a completed solve into the overrides list.
         *
         *     `snapshot_id` is either "final" or the 0-based index of an intermediate
         *     solve event from the last solve.
         */
        FillFromSnapshotRequest: {
            /**
             * Snapshot Id
             * @default final
             */
            snapshot_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Horizon */
        Horizon: {
            /**
             * N Days
             * @default 21
             */
            n_days: number;
            /** Public Holidays */
            public_holidays?: string[];
            /** Start Date */
            start_date?: string | null;
        };
        /** Hours */
        Hours: {
            /**
             * Weekday Am
             * @default 4
             */
            weekday_am: number;
            /**
             * Weekday Oncall
             * @default 12
             */
            weekday_oncall: number;
            /**
             * Weekday Pm
             * @default 4
             */
            weekday_pm: number;
            /**
             * Weekend Am
             * @default 4
             */
            weekend_am: number;
            /**
             * Weekend Consult
             * @default 8
             */
            weekend_consult: number;
            /**
             * Weekend Ext
             * @default 12
             */
            weekend_ext: number;
            /**
             * Weekend Oncall
             * @default 16
             */
            weekend_oncall: number;
            /**
             * Weekend Pm
             * @default 4
             */
            weekend_pm: number;
        };
        /** OverrideEntry */
        OverrideEntry: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Doctor */
            doctor: string;
            /** Role */
            role: string;
        };
        /** PrevWorkloadRequest */
        PrevWorkloadRequest: {
            /** Prev Roster Json */
            prev_roster_json: {
                [key: string]: unknown;
            };
        };
        /** RestSolveRequest */
        RestSolveRequest: {
            /**
             * Mode
             * @default new
             */
            mode: string;
            /**
             * Snapshot Assignments
             * @default false
             */
            snapshot_assignments: boolean;
        };
        /** SelfCheckViolation */
        SelfCheckViolation: {
            /** Location */
            location: string;
            /** Message */
            message: string;
            /** Rule */
            rule: string;
            /** Severity */
            severity: string;
        };
        /** SessionState */
        SessionState: {
            /** Blocks */
            blocks?: components["schemas"]["BlockEntry"][];
            constraints?: components["schemas"]["ConstraintsConfig"];
            /** Doctors */
            doctors?: components["schemas"]["DoctorEntry"][];
            horizon?: components["schemas"]["Horizon"];
            hours?: components["schemas"]["Hours"];
            /** Overrides */
            overrides?: components["schemas"]["OverrideEntry"][];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            soft_weights?: components["schemas"]["SoftWeights"];
            solver?: components["schemas"]["SolverSettings"];
            /** Stations */
            stations?: components["schemas"]["StationEntry"][];
            /** Subspecs */
            subspecs?: string[];
            tier_labels?: components["schemas"]["TierLabels"];
            workload_weights?: components["schemas"]["WorkloadWeights"];
        };
        /** SoftWeights */
        SoftWeights: {
            /**
             * Idle Weekday
             * @default 100
             */
            idle_weekday: number;
            /**
             * Oncall
             * @default 10
             */
            oncall: number;
            /**
             * Preference
             * @default 5
             */
            preference: number;
            /**
             * Reporting
             * @default 5
             */
            reporting: number;
            /**
             * Sessions
             * @default 5
             */
            sessions: number;
            /**
             * Weekend
             * @default 10
             */
            weekend: number;
            /**
             * Workload
             * @default 40
             */
            workload: number;
        };
        /**
         * SolveEvent
         * @description One improving solution found by CP-SAT.
         */
        SolveEvent: {
            /** Assignments */
            assignments?: components["schemas"]["AssignmentRow"][] | null;
            /** Best Bound */
            best_bound?: number | null;
            /** Components */
            components?: {
                [key: string]: number;
            };
            /** Objective */
            objective?: number | null;
            /**
             * Type
             * @default event
             * @constant
             */
            type: "event";
            /** Wall S */
            wall_s: number;
        };
        /** SolveResultPayload */
        SolveResultPayload: {
            /** Assignments */
            assignments?: components["schemas"]["AssignmentRow"][];
            /** Best Bound */
            best_bound?: number | null;
            /** First Feasible S */
            first_feasible_s?: number | null;
            /** Intermediate */
            intermediate?: components["schemas"]["SolveEvent"][];
            /** N Constraints */
            n_constraints: number;
            /** N Vars */
            n_vars: number;
            /** Objective */
            objective?: number | null;
            /** Penalty Components */
            penalty_components?: {
                [key: string]: number;
            };
            self_check?: components["schemas"]["SolverSelfCheck"] | null;
            /** Status */
            status: string;
            /** Wall Time S */
            wall_time_s: number;
        };
        /**
         * SolverSelfCheck
         * @description Automated post-solve hard-constraint audit. Every solve emits one;
         *     a green result is the feasibility receipt researchers and coordinators
         *     can trust. A non-green result means the model and the validator
         *     disagree — always a bug worth investigating.
         */
        SolverSelfCheck: {
            /** Ok */
            ok: boolean;
            /** Rules Failed */
            rules_failed?: string[];
            /** Rules Passed */
            rules_passed?: string[];
            /** Violation Count */
            violation_count: number;
            /** Violations */
            violations?: components["schemas"]["SelfCheckViolation"][];
        };
        /** SolverSettings */
        SolverSettings: {
            /**
             * Feasibility Only
             * @default false
             */
            feasibility_only: boolean;
            /**
             * Num Workers
             * @default 8
             */
            num_workers: number;
            /**
             * Time Limit
             * @default 60
             */
            time_limit: number;
        };
        /** StationEntry */
        StationEntry: {
            /** Eligible Tiers */
            eligible_tiers?: ("junior" | "senior" | "consultant")[];
            /**
             * Is Reporting
             * @default false
             */
            is_reporting: boolean;
            /** Name */
            name: string;
            /**
             * Required Per Session
             * @default 1
             */
            required_per_session: number;
            /** Sessions */
            sessions?: ("AM" | "PM")[];
        };
        /** TierLabels */
        TierLabels: {
            /**
             * Consultant
             * @default Consultant
             */
            consultant: string;
            /**
             * Junior
             * @default Junior
             */
            junior: string;
            /**
             * Senior
             * @default Senior
             */
            senior: string;
        };
        /** ValidateRequest */
        ValidateRequest: {
            /** Assignments */
            assignments: components["schemas"]["AssignmentRow"][];
        };
        /** ValidateResponse */
        ValidateResponse: {
            /** Ok */
            ok: boolean;
            /** Rules Failed */
            rules_failed: string[];
            /** Rules Passed */
            rules_passed: string[];
            /** Violation Count */
            violation_count: number;
            /** Violations */
            violations: components["schemas"]["Violation"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Violation */
        Violation: {
            /** Location */
            location: string;
            /** Message */
            message: string;
            /** Rule */
            rule: string;
            /** Severity */
            severity: string;
        };
        /** WorkloadWeights */
        WorkloadWeights: {
            /**
             * Weekday Oncall
             * @default 20
             */
            weekday_oncall: number;
            /**
             * Weekday Session
             * @default 10
             */
            weekday_session: number;
            /**
             * Weekend Consult
             * @default 25
             */
            weekend_consult: number;
            /**
             * Weekend Ext
             * @default 20
             */
            weekend_ext: number;
            /**
             * Weekend Oncall
             * @default 35
             */
            weekend_oncall: number;
            /**
             * Weekend Session
             * @default 15
             */
            weekend_session: number;
        };
        /** YamlExportResponse */
        YamlExportResponse: {
            /** Yaml */
            yaml: string;
        };
        /** YamlImportRequest */
        YamlImportRequest: {
            /** Yaml */
            yaml: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    diagnose_api_diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeasibilityIssueOut"][];
                };
            };
        };
    };
    explain_api_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainReport"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    fairness_api_metrics_fairness_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FairnessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fill_from_snapshot_api_overrides_fill_from_snapshot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FillFromSnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_roster_api_roster_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_sync_api_solve_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RestSolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveResultPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
        };
    };
    put_state_api_state_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionState"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_state_api_state_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_prev_workload_api_state_prev_workload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrevWorkloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_sample_api_state_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
        };
    };
    list_scenarios_api_state_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    load_scenario_api_state_scenarios__scenario_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_defaults_api_state_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
        };
    };
    export_yaml_api_state_yaml_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YamlExportResponse"];
                };
            };
        };
    };
    import_yaml_api_state_yaml_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YamlImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
